<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\log4net.config" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\log4net.config" />
  </ItemGroup>

  <ItemGroup>
    <!--更新程序会被塞进主程序的 exe 里，运行时单独释放出来，所以它自己也得打包成单文件-->
    <PackageReference Include="Costura.Fody" Version="5.7.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="log4net" Version="2.0.12" />
  </ItemGroup>

</Project>
